# Generated by Django 6.0.4 on 2026-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('BLOCK', 'Block'), ('UNBLOCK', 'Unblock'), ('ORDER_STATUS', 'Order Status Change'), ('PRICE_CHANGE', 'Price Change'), ('STOCK_UPDATE', 'Stock Update'), ('REPORT_EXPORT', 'Report Export')], max_length=30),
        ),
    ]
